component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/marauroa/.*
- ./bin/marauroa/client/.*
- ./bin/marauroa/client/net/.*
- ./bin/marauroa/common/.*
- ./bin/marauroa/common/crypto/.*
- ./bin/marauroa/common/game/.*
- ./bin/marauroa/common/game/doc-files/.*
- ./bin/marauroa/common/io/.*
- ./bin/marauroa/common/net/.*
- ./bin/marauroa/common/net/message/.*
- ./bin/marauroa/common/net/message/doc-files/.*
- ./bin/marauroa/functional/.*
- ./bin/marauroa/functional/basic/.*
- ./bin/marauroa/functional/load/.*
- ./bin/marauroa/ping/.*
- ./bin/marauroa/ping/client/.*
- ./bin/marauroa/ping/server/.*
- ./bin/marauroa/server/.*
- ./bin/marauroa/server/db/.*
- ./bin/marauroa/server/db/adapter/.*
- ./bin/marauroa/server/db/command/.*
- ./bin/marauroa/server/db/doc-files/.*
- ./bin/marauroa/server/game/.*
- ./bin/marauroa/server/game/container/.*
- ./bin/marauroa/server/game/db/.*
- ./bin/marauroa/server/game/dbcommand/.*
- ./bin/marauroa/server/game/messagehandler/.*
- ./bin/marauroa/server/game/python/.*
- ./bin/marauroa/server/game/rp/.*
- ./bin/marauroa/server/net/.*
- ./bin/marauroa/server/net/flood/.*
- ./bin/marauroa/server/net/nio/.*
- ./bin/marauroa/server/net/validator/.*
- ./bin/marauroa/tools/.*
- ./bin/marauroa/tools/protocolanalyser/.*
- ./extras/.*
- ./extras/template_website/.*
- ./extras/template_website/query/.*
- ./functional_tests/.*
- ./functional_tests/marauroa/.*
- ./functional_tests/marauroa/functional/.*
- ./functional_tests/marauroa/functional/basic/.*
- ./functional_tests/marauroa/functional/load/.*
- ./functional_tests/marauroa/ping/.*
- ./functional_tests/marauroa/ping/client/.*
- ./functional_tests/marauroa/ping/server/.*
- ./libs/.*
- ./tests/.*
- ./tests/marauroa/.*
- ./tests/marauroa/common/.*
- ./tests/marauroa/common/game/.*
- ./tests/marauroa/common/io/.*
- ./tests/marauroa/common/net/.*
- ./tests/marauroa/common/net/message/.*
- ./tests/marauroa/server/.*
- ./tests/marauroa/server/db/.*
- ./tests/marauroa/server/db/adapter/.*
- ./tests/marauroa/server/game/.*
- ./tests/marauroa/server/game/container/.*
- ./tests/marauroa/server/game/db/.*
- ./tests/marauroa/server/net/.*
